### ISSUE TITLE
Wheres it coming from

### ISSUE THREAD

**Issue by benny311** [sbcshop/motor-shield#9]
I am using a Raspberry Pi 3 Model B Vl. 2 and am using Python 3.5.3
Even when I insert the file directly from the code provided it keeps running into the same error
_________________________________________________________________________________
==================== RESTART: /home/pi/eduardo benitto.py ====================
Traceback (most recent call last):
  File "/home/pi/eduardo benitto.py", line 3, in <module>
    import PiMotor
ImportError: No module named 'PiMotor'
>>> 
________________________________________________________________________________
How do I Download the library so the code can be imported. also in the beginning where is the Import supposed to come FROM, in other words there is no FROM statement at the beguiling of the first two lines of code, if that is intentional what could be the problem. Thank you for your time.

**Comment by sbcshop** [comment]
Hi Benny,

This is due to PiMotor.py is not found. Please check the below link for PiMotor.py and place this library inside your folder.
https://github.com/sbcshop/motor-shield/blob/master/PiMotor.py

Or you can clone or download motor-shield repository for testing.
